spring:
    application:
        name: config-server
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/shaukatmakandar786/configuration_properties
server:
    port: 9093

