server:
    port: 8081
spring:
    application:
        name: Welcome-Service
    boot:
        admin:
            client:
                url: http://localhost:1111/
management:
    endpoints:
        web:
            exposure:
                include: '*'
# When we not use the port 8761 to the eureka server application then we will use below properties to register client application to eureka server
#eureka:
#    client:
#        service-url:
#            defaultZone: http://localhost:8761/eureka/